	

    // there have been some name changes, so there are duplicates. ex.: tailsthefaggot and tails
    // also, "feel", "feelsbadman" and "feelsgoodman" can now be clicked
    //
    // changed emote names (originals still exist): tails, jew, taco, fickdich, van, 9gag, push, feel, feelsgud
    // october 31, 2013 - added 5 emotes and changed some dimensions on a few
    var $codes =
    {
        "dewbunker" : '<img src="http://i.imgur.com/GWYXYBp.gif" width="32" height="46">',
        "cool" : '<img src="http://i.imgur.com/oh9I5dq.png" width="53" height="49">',
        "tailsthefaggot" : '<img src="http://i.imgur.com/2WKyq8T.png" width="53" height="49">',
        "tails" : '<img src="http://i.imgur.com/2WKyq8T.png" width="53" height="49">',
        "slav" : '<img src="http://i.imgur.com/DWp3VOQ.gif" width="45" height="46">',
        "stepfather" : '<img src="http://i.imgur.com/1PvWGzC.png" width="43" height="69">',
        "dolan" : '<img src="http://i.imgur.com/NF0yh.png" width="44" height="45">',
        "ameer" : '<img src="http://i.imgur.com/zg7DE.gif" width="50" height="58">',
        "jew" : '<img src="http://i.imgur.com/zg7DE.gif" width="50" height="58">',
        "ready" : '<img src="http://i.imgur.com/jWLjv.gif" width="43" height="59">',
        "usa" : '<img src="http://i.imgur.com/tSXNh.gif" width="60" height="42">',
        "#bump" : '<img src="http://i.imgur.com/d1odx.png" width="25" height="25">',
        "birry" : '<img src="http://i.imgur.com/DduoO.gif" width="33" height="53">',
        "dog" : '<img src="http://i.imgur.com/OcGfN.gif" width="53" height="53">',
        "=/" : '<img src="http://i.imgur.com/d1odx.png" width="25" height="25">',
        "gaben" : '<img src="http://i.imgur.com/T5SCh.gif" width="43" height="54">',
        "taco" : '<img src="http://i.imgur.com/5OVAa.png" width="39" height="54">',
        "doingitwell" : '<img src="http://i.imgur.com/5OVAa.png" width="39" height="54">',
        "fuckyou" : '<img src="http://i.imgur.com/mI0do.png" width="39" height="56">',
        "fickdich" : '<img src="http://i.imgur.com/mI0do.png" width="39" height="56">',
        "3" : '<img src="http://i.imgur.com/Aav23.png" width="35" height="36">',
        "burd" : '<img src="http://i.imgur.com/kQcjC.gif" width="35" height="36">',
        "snoop" : '<img src="http://i.imgur.com/Bmsp9.gif" width="23" height="50">',
        "jimmies" : '<img src="http://i.imgur.com/gQB3S.gif" width="35" height="38">',
        "sanic" : '<img src="http://i.imgur.com/D42Om.png" width="50" height="45">',
        "america" : '<img src="http://i.imgur.com/3Wxtk.gif" width="36" height="56">',
        "dilbert" : '<img src="http://i.imgur.com/WteuLYV.gif" width="56" height="55">',
        "loading" : '<img src="http://i.imgur.com/LpBOu.gif" width="53" height="54">',
        "van" : '<img src="http://i.imgur.com/wJk3i.gif" width="33" height="53">',
        "deepdarkfantasy" : '<img src="http://i.imgur.com/wJk3i.gif" width="33" height="53">',
        "satan" : '<img src="http://i.imgur.com/W9XSh.gif" width="43" height="54">',
        "bioware" : '<img src="http://i.imgur.com/1K4gw.gif" width="41" height="48">',
        "shazbot" : '<img src="http://i.imgur.com/W4Ynk.png" width="41" height="48">',
        "reddit" : '<img src="http://i.imgur.com/wKaFk.png" width="80" height="16">',
        "9gag" : '<img src="http://i.imgur.com/wKaFk.png" width="80" height="16">',
        "bestkorea" : '<img src="http://i.imgur.com/Kd2oh.gif" width="43" height="54">',
        "assntitties" : '<img src="http://i.imgur.com/CALcK.png" width="38" height="42">',
        "hitoame" : '<img src="http://i.imgur.com/ofu37.gif" width="55" height="50">',
        "penis" : '<img src="http://i.imgur.com/VorSn.gif" width="50" height="58">',
        "duane" : '<img src="http://i.imgur.com/oCCMY.gif" width="70" height="47">',
        "plzgo" : '<img src="http://i.imgur.com/ilhsw.png" width="46" height="55">',
        "no" : '<img src="http://i.imgur.com/nKa8o.png" width="41" height="30">',
        "idontwantthat" : '<img src="http://i.imgur.com/nKa8o.png" width="41" height="30">',
        "keke" : '<img src="http://i.imgur.com/Pf0Xa.png" width="43" height="44">',
        "uncle" : '<img src="http://i.imgur.com/oIBaE.jpg" width="44" height="52">',
        "reshiram" : '<img src="http://i.imgur.com/nrGTe.gif" width="44" height="50">',
        "push" : '<img src="http://i.imgur.com/98R1p.gif" width="43" height="49">',
        "ohshitimsorry" : '<img src="http://i.imgur.com/98R1p.gif" width="43" height="49">',
        "autism" : '<img src="http://i.imgur.com/9QfYC.gif" width="55" height="55">',
        "juggalo" : '<img src="http://i.imgur.com/qZpT3.gif" width="43" height="49">',
        "dewritos" : '<img src="http://i.imgur.com/cRRtv.jpg" width="39" height="57">',
        "stanza" : '<img src="http://i.imgur.com/1WRTO.png" width="41" height="58">',
        "bestgames" : '<img src="http://i.imgur.com/ImyXj.png" width="48" height="54">',
        "gamestop" : '<img src="http://i.imgur.com/kpJu4.gif" width="65" height="33">',
        "o" : '<img src="http://i.imgur.com/WifGe.gif" width="34" height="34">',
        "fothegrove" : '<img src="http://i.imgur.com/wqwV1.gif" width="35" height="38">',
        "aliens" : '<img src="http://i.imgur.com/QN73Y.gif" width="50" height="57">',
        "go" : '<img src="http://i.imgur.com/aqhrV.gif" width="50" height="38">',
        "pomf" : '<img src="http://i.imgur.com/LuPK4.png" width="41" height="46">',
        "kreayshawn" : '<img src="http://i.imgur.com/otpxf.png" width="41" height="51">',
        "bodywash" : '<img src="http://i.imgur.com/eEGbx.png" width="41" height="51">',
        "goblinu" : '<img src="http://i.imgur.com/PhwbA.jpg" width="55" height="38">',
        "nogaems" : '<img src="http://i.imgur.com/rjSeG.gif" width="47" height="57">',
        "feel" : '<img src="http://i.imgur.com/4lwg0.png" onclick="this.src = \'http://i.imgur.com/BZ3WF.png\'">',
        "feelsbadman" : '<img src="http://i.imgur.com/4lwg0.png" onclick="this.src = \'http://i.imgur.com/BZ3WF.png\'">',
        "feelsgoodman" : '<img src="http://i.imgur.com/BZ3WF.png" onclick="this.src = \'http://i.imgur.com/4lwg0.png\'">',
        "feelsgud" : '<img src="http://i.imgur.com/BZ3WF.png" onclick="this.src = \'http://i.imgur.com/4lwg0.png\'">',
        "alien" : '<img src="http://i.imgur.com/Zrgc1.gif" width="40" height="60">',
        "bomb" : '<img src="http://i.imgur.com/1Ri01.png" width="30" height="44">',
        "dreck" : '<img src="http://i.imgur.com/aj3bd.png" width="43" height="32">',
        "skeleton" : '<img src="http://i.imgur.com/bDvOj.gif" width="50" height="38">',
        "pumpkindance" : '<img src="http://i.imgur.com/sXZiA.gif" width="60" height="42">',
        "2spooky" : '<img src="http://i.imgur.com/VN8Gn.gif" width="80" height="20">',
        "gooby" : '<img src="http://i.imgur.com/V794a.jpg" width="55" height="54">',
        "dosh" : '<img src="http://i.imgur.com/oL6u9.png" width="50" height="58">',
        "8bitdose" : '<img src="http://i.imgur.com/n4sEL.gif" width="46" height="42">',
        "costanza" : '<img src="http://i.imgur.com/7VYoq.png" width="41" height="58">',
        "mysides" : '<img src="http://i.imgur.com/vETtK.png" width="39" height="58">',
        "pikminu" : '<img src="http://i.imgur.com/VLgKCzM.png" width="43" height="55">',
        "el" : '<img src="http://i.imgur.com/6H5Nu1u.gif" width="27" height="25">',
        "ravi" : '<img src="http://i.imgur.com/Ogg9hCU.gif" width="43" height="31">',
        "umirin" : '<img src="http://i.imgur.com/6J28Z.jpg" width="43" height="52">',
       
        "bearfight" : '<img src="http://i.imgur.com/JVbAzkh.gif" width="35" height="58">',
        "spurdance" : '<img src="http://i.imgur.com/Z0wSJcd.gif" width="35" height="60">',
        "why" : '<img src="http://i.imgur.com/cV3YW2a.png" width="48" height="48">',
        "chen" : '<img src="http://i.imgur.com/0lJXT.png" width="50" height="46">',
        "rip" : '<img src="http://i.imgur.com/3Nzl3gQ.gif" width="50" height="63">',
        "dante" : '<img src="http://i.imgur.com/I0hWD8T.png" width="60" height="54">',
        "rattle" : '<img src="http://i.imgur.com/Dg2oYOp.gif" width="57" height="40">',
        "cat" : '<img src="http://i.imgur.com/YftOX.png" width="60" height="60">',
        "spurdo" : '<img src="http://i.imgur.com/dlNRc8B.png" width="51" height="39">',
        "thedick" : '<img src="http://i.imgur.com/ul0UQ.png" width="50" height="50">',
        "octagon" : '<img src="http://i.imgur.com/d3cA4Ul.png" width="50" height="47">',
        "stop" : '<img src="http://i.imgur.com/d3cA4Ul.png" width="50" height="47">',
        "brobill" : '<img src="http://i.imgur.com/wN51qwe.gif" width="50" height="45">',
        "miku" : '<img src="http://i.imgur.com/D1tLhyU.gif" width="45" height="45">',
        "miku2" : '<img src="http://i.imgur.com/MtVbD.gif" width="50" height="63">',
        "o-o" : '<img src="http://i.imgur.com/rH7gBZ2.gif" width="45" height="45">',
        "kitty" : '<img src="http://i.imgur.com/bRUVd.gif" width="50" height="50">',
        "manboss" : '<img src="http://i.imgur.com/Pg9oejU.gif" width="55" height="50">',
        "turkey" : '<img src="http://i.imgur.com/7kcpMQp.png">',
        "fresh" : '<img src="http://i.imgur.com/mSDGeAp.gif" width="40" height="50">',
        "morefags" : '<img src="http://i.imgur.com/RTAfNKB.gif" width="35" height="50">',
        "data" : '<img src="http://i.imgur.com/FsLt3aK.gif" width="25" height="40">',
        "doge" : '<img src="http://i.imgur.com/JwavFI0.jpg" width="53" height="53">',
        /*"fastsanic" : '<marquee behavior="scroll" direction="right" scrollamount="40"><img src="http://i.imgur.com/D42Om.png" width="50" height="45">', Disabled*/
     
        "obama" : '<img src="http://i.imgur.com/0knI1p2.gif" width="60" height="46">',
        "osama" : '<img src="http://i.imgur.com/tt3WcjK.png" width="40" height="54">',
        "ohlawd" : '<img src="http://i.imgur.com/LJyau7C.png" width="50" height="45">',
        "slam" : '<img src="http://i.imgur.com/VHFPkCo.png" width="41.25" height="50">',
        "rage" : '<img src="http://i.imgur.com/tAQInNX.jpg" width="45" height="45">',
        "happening" : '<img src="http://i.imgur.com/642PjCs.gif">',
        "33" : '<img src="http://i.imgur.com/ndmRRor.png">',
        "mfw" : '<img src="http://i.imgur.com/hJiAJPJ.png" width="45" height="50">',
        "jaffa" : '<img src="http://i.imgur.com/zlxankN.jpg" width="43" length="51">',
        "nice" : '<img src="http://i.imgur.com/UsUdb.png" width="60" length="60">',
        "pekaface" : '<img src="http://i.imgur.com/0nDMlfQ.png">',
        "haveaseat" : '<img src="http://i.imgur.com/0YH5oDz.jpg" width="60" height="52">',
        "bogs" : '<img src="http://i.imgur.com/NHWMFAV.png" width="47.5" height="62.5">',
        /*old dilbert: http://i.imgur.com/LspyD.gif*/
       
        "wut" : '<img src="http://i.imgur.com/HgIqmtS.png">',
        "kfc" : '<img src="http://i.imgur.com/dOpm4Vg.gif" width="60" height="47">',
        "meeku" : '<img src="http://i.imgur.com/YQSESo6.png" width="45" height="60">',
        "jii" : '<img src="http://i.imgur.com/zG59d7Q.png" width="52" height="40">',
        "spherical" : '<img src="http://i.imgur.com/ejyx6KU.png" width="48" height="66">',
        "▲" : '<img src="http://i.imgur.com/tcNC8l3.gif" width="70" height="47">',
        "nope" : '<img src="http://i.imgur.com/3oMMfGR.gif" width="63" height="47">',
        "whatastory" : '<img src="http://i.imgur.com/NEW7dXq.png" width="49" height="45">',
         "doot" : '<img src="http://i.imgur.com/BhunL.gif" width="50" height="50">',
        "twerk" : '<img src="http://i.imgur.com/cG2guE8.gif" width="53" height="67">',
        "heero" : '<img src="http://i.imgur.com/2Y8mUxP.png" width="65" height="60">'  
    };

